import Head from 'next/head'
import { ScriptProps } from 'next/script'
import styled from 'styled-components'

const StyledMain = styled.main`
  margin: 0 auto;
  background-color: #F4F8F7;
  height: 100vh;
  /* max-width: 1300px; */
`

const BaseLayout = ({ children }: ScriptProps) => {
  return (
    <div id="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <StyledMain>{children}</StyledMain>
    </div>
  )
}

export default BaseLayout
